### ISSUE TITLE
Index Error

### ISSUE THREAD

**Issue by Sandlavish** [MaximIntegratedAI/ai8x-training#101]
I got an index error after I ran the following line of code:
python gen_vggface2_embeddings.py -r <path_to_vggface2_dataset_folder> -d <path_to_store_generated_dataset> --type train

IndexError: The shape of the mask [58] at index 0 does not match the shape of the indexed tensor [59, 4] at index 0.

**Comment by Sandlavish** [comment]
I am getting a similar index error on running the following command:
python gen_youtubefaces_embeddings.py -r <path_to_youtubefaces_dataset_folder> -d <path_to_store_generated_dataset> --type train/test
IndexError: The shape of the mask [111] at index 0 does not match the shape of the indexed tensor [112, 4] at index 0

**Comment by ermanok** [comment]
I cannot reproduce the error. Can you give more details about how and at which stage of the execution you get this error? Also please be sure using the 'develop' branch of the repo and having the dataset VGGFace-2 not VGGFace...

**Comment by Sandlavish** [comment]
So I am using VGGFace-2 dataset and not VGGFace and I am sure that I am using the develop branch of the repo. 
Here are the steps following which I am getting the error:
- Open terminal
- cd $AI_PROJECT_ROOT (to change to the project root)
- cd ai8x-training
- git checkout develop
- git submodule update --init
- pyenv local 3.8.10
- python3 -m venv .
- source bin/activate      (to activate the training environment)
- cd dataset/face_id     (because embeddings.py is inside the face_id folder)
- python3 gen_vggface2_embeddings.py -r /home/user/Documents/Source/AI/ai8x-training/datasets/face_id/VGG-Face2/vggface2_train -d /home/user/Documents/Source/AI/ai8x-training/store --type train

Index Error: IndexError: The shape of the mask [35] at index 0 does not match the shape of the indexed tensor [36, 4] at index 0


Note: I downloaded the VGGFACE-2 dataset from a different source because the link provided in the readme file is no longer available. But that shouldn't be an issue since I am getting the same index error for Youtube Faces dataset and I downloaded that from the source given in the readme file.

**Comment by ermanok** [comment]
After activating environment you have to call the following two lines in order to install the required python packages:
- pip3 install -U pip setuptools
- pip3 install -U -r requirements.txt # or requirements-cu11.txt with CUDA 11.x

**Comment by Sandlavish** [comment]
I did that while setting up the virtual environments for the first time. Do I need to run those commands every time I activate the environment?

**Comment by ermanok** [comment]
No, it is a one time thing to install the packages. Then, it might be due to the downloaded dataset. Can you share the full log of the error (so I can see in which package and line you get the error) and the link for the dataset?

**Comment by Sandlavish** [comment]
So the link to VGG-Face2 dataset given in the readme file: https://www.robots.ox.ac.uk/~vgg/data/vgg_face2/  doesn't work.
Therefore, I downloaded the dataset from the following link: https://academictorrents.com/details/535113b8395832f09121bc53ac85d7bc8ef6fa5b

I tried to find the error logs but couldn't find the latest ones. Do you know where I can find them?

**Comment by ermanok** [comment]
Thanks for the link. You can share the full error trace on the console.

**Comment by Sandlavish** [comment]
![image0](https://user-images.githubusercontent.com/68152137/129069742-498a69a8-5e6c-4511-90ef-2518d4f788e8.jpeg)

**Comment by Sandlavish** [comment]
Sorry, for some reason, I am having trouble sharing the full error trace. Therefore, I decided to share the screenshot!

**Comment by ermanok** [comment]
I could only download the test set from the link you provided. I could not replicate the error. Here are the steps I followed:
1. Download the files in the link to <vgg_folder>
	- The folder content is: {'data/', 'meta/', 'README.md', 'README.txt'}
2. Go to <vgg_folder>/data and run 'tar -xf vggface2_test.tar.gz'
	- This creates a folder 'test' under <vgg_folder>/data
3. Go to <ai8x-training-repo-folder>/datasets/face-id and run 'python3 gen_vggface2_embeddings.py -r /data/ml/VGGFace-2 -d ../../store --type test'
	- This creates a test folder with the required content under <ai8x-training-repo-folder>/store folder
	
If you still get an error after these steps, please be sure you are sync the develop branch of the repo with the latest content with git fetch + git pull. Also please check the data you downloaded is not corrupted.

**Comment by justp7** [comment]
I encountered the same problem in operation. Have you solved it?

**Comment by justp7** [comment]
Now I use the GPU of the cloud server for training, but this error does not occur. It is probably caused by insufficient cache of the graphics card.
