### ISSUE TITLE
Feature request: Automatic YAML generator

### ISSUE THREAD

**Issue by Narduzzi** [MaximIntegratedAI/ai8x-training#137]
Hello,

I would like to create my own model in PyTorch and port it to the MAX78000FTHR.
However, I don't exactly understand how to deal with the YAML architecture files (especially processors).

Is there any strategy on how to deal with the processors when the model contains parallel branches (3 residual connections)?
Is it possible to create a script that automatically generates the YAML file according to the PyTorch implementation of the model? This would really make the embedding process easier.

Thanks for the help!

**Comment by rotx-maxim** [comment]
(Assuming you've read the quick start and the question is more involved; https://github.com/MaximIntegratedAI/MaximAI_Documentation/blob/master/Guides/YAML%20Quickstart.md)

Unfortunately, there is no automated process at this time (it is theoretically possible but very difficult); there are interactions between data memory, processors, and weight memories. Aside from starting with an existing model, we would be happy to help with any specific model.
