### ISSUE TITLE
Continue the training process from LOGS

### ISSUE THREAD

**Issue by oussemajelassi** [MaximIntegratedAI/ai8x-training#162]
Hey I launched the train_kws20_v3.sh file and it took a while "gathering dataset from existing raw data" as it mentioned, reaching 20/35 it crashed and showed a "killed" message. Now i want to resume the process from that logs folder what can I do ?

**Comment by aniktash** [comment]
you can add to the training script: --resume-from your_checkpoint.pth.tar

**Comment by oussemajelassi** [comment]
what should I do so it only process 6 keywords instead of all 35 ?

**Comment by aniktash** [comment]
There is already a 6-word implementation. You can change the dataset name in the training .sh script to: --dataset KWS
You may need to update the model to reflect the output classes in the linear layer at the end. 
Alternatively, you can keep the same 20 keywords, but reduce the augmentation factor inside KWS_getdataset function to: 
augmentation = {'aug_num': 0}. This will reduce the size of dataset by 3x
