### ISSUE TITLE
KWS20

### ISSUE THREAD

**Issue by oussemajelassi** [MaximIntegratedAI/ai8x-training#163]
What Should I change in order to process only 6 labels and not all 35 ?

**Comment by aniktash** [comment]
There is already a 6-word implementation. You can change the dataset name in the training .sh script to: --dataset KWS
You may need to update the model to reflect the output classes in the linear layer at the end.
Alternatively, you can keep the same 20 keywords, but reduce the augmentation factor inside KWS_getdataset function to:
augmentation = {'aug_num': 0}. This will reduce the size of dataset by 3x

**Comment by aniktash** [comment]
You may also check this out with instructions on modifying KWS dataset: https://github.com/MaximIntegratedAI/MaximAI_Documentation/blob/master/Guides/Making%20Your%20Own%20Audio%20and%20Image%20Classification%20Application%20Using%20Keyword%20Spotting%20and%20Cats-vs-Dogs.md#making-your-own-audio-and-image-classification-application-using-keyword-spotting-and-cats-vs-dogs-examples

**Comment by oussemajelassi** [comment]
Thaaanks ❤️

**Comment by oussemajelassi** [comment]
Hello i was following the instructions and running this python convert_segment_wav.py -i INPUT_FOLDER -o OUTPUT_FOLDER got me into a "No such file or directory" error where can i find this file please ? thanks in advance ❤️

**Comment by aniktash** [comment]
Attached here:
[kws-util.zip](https://github.com/MaximIntegratedAI/ai8x-training/files/9212087/kws-util.zip)

If you need ffmpeg, you can find it here:
https://ffmpeg.org/download.html

**Comment by oussemajelassi** [comment]
Thank your for efforts ❤️

**Comment by oussemajelassi** [comment]
About that speed_pitch_change.py file what command do I Use for it ? THANKS IN ADVANCE ❤️

**Comment by aniktash** [comment]
It's a very simple script.  Just put all your 1-sec  wav files in a "WavFilesSegmented" folder and it will change the pitch and write in "WavFilesSegmentedOUT" folder.
