### ISSUE TITLE
KWS model training

### ISSUE THREAD

**Issue by oussemajelassi** [MaximIntegratedAI/ai8x-training#167]
Hello Whenever I run Scripts/train_kws20_v3.sh i get this error "ResourceWarning: unclosed file <_io.BufferedReader name=12>" right after downloading and extracting the labels.
Any Ideas ? thanks in advance.

**Comment by oussemajelassi** [comment]
the exact error is this : 
Traceback (most recent call last):
  File "/mnt/c/users/ousjl/desktop/maxim/ai8x-training/venv/lib/python3.8/site-packages/audioread/__init__.py", line 86, in available_backends
    if ffdec.available():
ResourceWarning: unclosed file <_io.BufferedReader name=12>

**Comment by aniktash** [comment]
Try to sync up with the repo and update distiller submodule.  Maybe it's related to the GPU if you have one but have not installed the cuda driver? You can try to add --cpu to the training script to force using only CPU to test.

**Comment by prerna-khanna** [comment]
I am still getting this error after updating distiller, syncing up the repo, and trying --cpu. Any updates on this?
Thanks!

**Comment by aniktash** [comment]
First, let's make sure you have correct librosa and audioread with $pip3 list:
audioread               2.1.9
librosa                 0.9.2

The dataloader uses librosa to load the audio files, librosa uses audioread module and this error comes from ffdec.py in audioread when it tries to check if **FFmpeg and AVConv** are available by reading their version "ffpmeg -version" or "avconv -version".  I'm not sure which one fails.
You may want to manually check ffmpeg and avcon version in the commandline to see if any error happens. 
If you have other audio tasks running or not properly closed that are using either of them, it could cause this error. 
You may also uninstall ffmpeg and avconv and try again. Then ffdec.py checks if they are available, and if not it should proceed.
