### ISSUE TITLE
KWS training 

### ISSUE THREAD

**Issue by prerna-khanna** [MaximIntegratedAI/ai8x-training#175]
Hi,

I am having this issue while running all the KWS training examples:

    ResourceWarning: unclosed file <_io.BufferedReader name=48>
    Exception ignored in: <_io.FileIO name=46 mode='rb' closefd=True>
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.8/site-packages/audioread/__init__.py", line 86, in available_backends
        if ffdec.available()

I have synced up the repository and updated it to the latest version of the distiller. Also, this error remains while using the --cpu option.
Any help on this issue would be great.
Thanks!

**Comment by rotx-maxim** [comment]
You are using Conda instead of Pip. This could cause conflicts. It's also possible that you did not activate the virtual environment. Could you make sure you follow all the installation instructions?

**Comment by aniktash** [comment]
Please also check : https://github.com/MaximIntegratedAI/ai8x-training/issues/167#issuecomment-1238486937
