### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by salihtangel** [MaximIntegratedAI/ai8x-training#176]
I want to test a model with my dataset. (Not train only test) . I trained  a model and record it. But i could not handle test. How to do that?
How do i test an trained model.

**Comment by rotx-maxim** [comment]
Could you take a look at the video tutorials at https://www.maximintegrated.com/en/products/microcontrollers/artificial-intelligence.html/tab4
There are examples in the training repository under scripts (look at "evaluate_..."), but the videos and README.md have a better explanation of how the pieces fit together.
