### ISSUE TITLE
KWS training

### ISSUE THREAD

**Issue by oussemajelassi** [MaximIntegratedAI/ai8x-training#182]
Hello i was iwondering if training the model using recorded samples from the max microphone will increase the accuracy ? 
I mean training the model with same microphone it will be tested on in real life ? 
If yes can you provide us with necessary steps to do so ?

**Comment by aniktash** [comment]
Hi,
Yes, it helps.  Please see the attached code. In the main.c, you can send out the samples that are used for inference if #define SEND_MIC_OUT_SERIAL is enabled. 
The capture_serial_bin.py script receives serial data and creates  .wav files that can be added to your dataset. Please update the COM port in the script. 
[kws21_demo_mic_capture.zip](https://github.com/MaximIntegratedAI/ai8x-training/files/9620931/kws21_demo_mic_capture.zip)

**Comment by aniktash** [comment]
Please update the keywords[NUM_OUTPUT][10] according to your trained keywords.

**Comment by aniktash** [comment]
I tried 0.10.3.
The latest 0.11.0 should probably be fine too.

**Comment by oussemajelassi** [comment]
Thank youu
