### ISSUE TITLE
Faceid training and evaluation: tensor size mismatch when batch size > 1

### ISSUE THREAD

**Issue by lx2u16** [MaximIntegratedAI/ai8x-training#184]
Hi, I am currently trying to run the training and evaluation scripts of faceid. They only work when I set batch size 1, and other sizes will give me this tensor size mismatch error. 

e.g. with batch size 100

> Traceback (most recent call last):
File "train.py", line 1794, in <module>
    main()
  File "train.py", line 438, in main
    return evaluate_model(model, criterion, test_loader, pylogger, activations_collectors,
  File "train.py", line 1495, in evaluate_model
    top1, _, _, _, mAP = test(test_loader, model, criterion, loggers, activations_collectors,
  File "train.py", line 958, in test
    top1, top5, vloss, APs, mAP = _validate(test_loader, model, criterion, loggers, args)
  File "train.py", line 1163, in _validate
    classerr.add(output.data.permute(0, 2, 3, 1).flatten(start_dim=0,
  File "/opt/conda/lib/python3.8/site-packages/torchnet/meter/msemeter.py", line 21, in add
    self.sesum += torch.sum((output - target) ** 2)
RuntimeError: The size of tensor a (512) must match the size of tensor b (51200) at non-singleton dimension 1

Could you please give me some help on how to fix this? Thanks.

**Comment by justp7** [comment]
By modifying lines 779 and 1111 of the train.py file, I change `classerr.add(output.data.permute(0, 2, 3,1).flatten(start_dim=0,end_dim=2),target.flatten())` to `classerr.add(output.data, target)` , Now it's working properly!
I don't know if this is correct, but it works!
With best wishes.

**Comment by ermanok** [comment]
Commit #187 fixes that issue. thanks for reporting.
