### ISSUE TITLE
CamVid-UNet accuracy measurement

### ISSUE THREAD

**Issue by lx2u16** [MaximIntegratedAI/ai8x-training#186]
Hi,

I can see there is an UNet demo that is trained and tested using the CamVid dataset. I think it is doing semantic segmentation which the accuracy is typically measured by IoU. 

However, your script shows a top1 accuracy. I wonder what it is?

Thanks.

**Comment by ermanok** [comment]
The dataset gives a segmentation map, where each pixel is assigned to one of the target classes, of the image as the label. So we use pixel-wise classification accuracy as the Top-1 accuracy.

**Comment by lx2u16** [comment]
@ermanok thanks, and the final Top-1 accuracy is the mean pixel-wise classification accuracy of the entire test dataset?

**Comment by ermanok** [comment]
that is correct.
