### ISSUE TITLE
Have anyone tried some kind of anomaly detection on The max78000 ? I mean there are plenty of examples on  ARDUINO/ ESP but none on MAXIM !

### ISSUE THREAD

**Issue by oussemajelassi** [MaximIntegratedAI/ai8x-training#192]

**Comment by rotx-maxim** [comment]
Of course you can do anomaly detection on MAX7800X. Unless you have a comprehensive data set that represents all the various failure mechanisms, we recommend using an auto encoder and training it on "normal" system state.

**Comment by oussemajelassi** [comment]
Thank you for your feedback, Is it the same process of training / synthesis as in any other example you showed before or are are there others steps to do ? Thanks in advance !
