### ISSUE TITLE
MaxPool1D stride assertion error/keyword argument naming collision

### ISSUE THREAD

**Issue by timber77** [MaximIntegratedAI/ai8x-training#194]
Hi

I think there might be a problem in the MaxPool1D class. Especially in the keyword arguments naming going up/down the class hierarchy.

![grafik](https://user-images.githubusercontent.com/32300343/204802159-e6257f98-ce8e-45f6-a07c-0d8a9f27a072.png)
![grafik](https://user-images.githubusercontent.com/32300343/204802282-02a37a2e-5911-4a02-8152-23667ed76071.png)
![grafik](https://user-images.githubusercontent.com/32300343/204804487-b3b3174f-cdbf-4ec3-9e1f-27aa30a0413d.png)

In the Conv1D class if Pooling is not None there is an assertion at the end to check that stride == 1.  Since the default value for stride is 3 an explicit setting is needed. Setting stride when using the MaxPool1D seems impossible as the stride keyword in the MaxPool1D gets used as the pooling_stride(line 1262).

**Comment by ermanok** [comment]
Thanks for reporting the issue. The above fix should solve the issue..
