### ISSUE TITLE
custom activation function

### ISSUE THREAD

**Issue by nikky4D** [MaximIntegratedAI/ai8x-training#235]
Is it possible to use a different activation function than relu/abs? I would like to use Mish/Swish/Leaky Relu. Is it possible to use these for the Max78002

**Comment by rotx-maxim** [comment]
The hardware supports `ReLU`, `Abs`, and `None`, see https://github.com/MaximIntegratedAI/ai8x-training#activation-functions
Please note that due to clipping even `None` has two non-linearities.
