### ISSUE TITLE
Are depthwise ConvTranspose2d Layers supported?

### ISSUE THREAD

**Issue by alvarosca** [MaximIntegratedAI/ai8x-training#238]
While creating a custom model I tried to use the "groups" argument for a ConvTranpose2d layer but it had no effect. I checked the ai8x.py code and apparently the argument is missing as shown in the following:

![convtranspose2d](https://github.com/MaximIntegratedAI/ai8x-training/assets/86563336/6c6a837e-08c1-480c-ba66-e744695ec57e)

I just want to confirm if the groups argument is not present for a reason or if I just add it manually I shouldn't have problems when it comes to synthetizing the model.

**Comment by ermanok** [comment]
Hello,

Thanks for reporting the issue. For MAX78000, the  'group' must be 1 and for MAX78002 it should be either 1 or number of channels. For which device you are facing this issue? You can also share your code, yaml file, checkpoint and izer script and I can go over the issue. Thanks.

**Comment by alvarosca** [comment]
I'm working with a MAX78002. I'm using depth-wise transpose convolutions ( so groups==in_channels==out_channels ). As described above, the current version of ai8x.py is lacking the 'groups' argument when defining the conv2dtranspose layer so the following two layers give out the same result:

**Comment by ermanok** [comment]
So, you tested the model on MAX78002 as well, right? Or do you also have an issue with the synthesized model?

**Comment by alvarosca** [comment]
No, there were no issues in the synthesized model. The problem is that when you define a ConvTranspose2d layer on the training environment using the ai8x.ConvTranspose2d() class, the groups argument has no effect.

 Just so we are clear, from my end the problem is solved, but I had to modify the ai8x.py code to make it work. 

In order to avoid someone else encountering the problem in the future what I propose is to simply modify the part of the ai8x.py code where the ConvTranspose2d class is defined as shown below so that the 'Groups' argument actually works. In the current version of the repository the argument is missing. See line 766 of aix8.py:

![convtranspose2d_](https://github.com/MaximIntegratedAI/ai8x-training/assets/86563336/4fe07d7a-5357-48f9-a1f9-0a6ea2263dd8)

**Comment by rotx-maxim** [comment]
Resolved in #241
