### ISSUE TITLE
The numbers of neural network layers with MAX78000

### ISSUE THREAD

**Issue by jason850124** [MaximIntegratedAI/ai8x-training#246]
I saw the description of the ai8x-training which mentioned the neural network layers of max78000 up to 32, but the max78000 datasheet said it can up to 64 layers, so which is the right one? Thank you.

Best regards,
Jason

**Comment by rotx-maxim** [comment]
It's 32 "hardware" layers. However, logically, each of those hardware layers can do more than one thing - for example, element wise addition, pooling, and convolution (that would be 96 layers). The data sheet number presents a reasonable estimate for an average count for typical networks.

**Comment by jason850124** [comment]
Hi! Rotx,

Thanks for your reply! I totally understand now! 

Best regards,
Jason
