### ISSUE TITLE
ModuleNotFoundError: No module named 'resource'

### ISSUE THREAD

**Issue by sugspi** [MaximIntegratedAI/ai8x-training#248]
Hi, 
I ran `train.py` in windows 10 naitive enviroment and got an error: `ModuleNotFoundError: No module named 'resource'`.

The cause was the added `import resource`.

I commented out the import resource related lines (L140-L144) and it works as before.
https://github.com/MaximIntegratedAI/ai8x-training/blob/6ad19921c68bbd1a1e192b329666e79b2e71abce/train.py#L63

**Comment by rotx-maxim** [comment]
Thanks for reporting this. Does #249 fix the issue for you?

**Comment by sugspi** [comment]
It works. Thank you.
