### ISSUE TITLE
help to understand use of wide scores/locations in the fpn detector

### ISSUE THREAD

**Issue by nikky4D** [MaximIntegratedAI/ai8x-training#252]
In the fpndetector.py, there are 2 functions for the classification and regression net that use wide_scores and wide_locations. what are these variables and why do we need them here, and if we change the input to the model (using a different image modality eg not RGB, or making the image bigger, does this change the need for the wide_scores or wide_locations?

``` 
In the FPN definition we have:

        self.classication_net = ClassificationModel(num_classes=self.num_classes, num_anchors = self.num_anchors, feature_size=self.feature_size, wide=wide_scores, **kwargs)
        self.regression_net = RegressionModel(feature_size=self.feature_size, num_anchors=self.num_anchors, wide=wide_locations, **kwargs)
```

Also these 2 functions return the conv wide feature
```
    def are_locations_wide(self):
        """
        Returns whether model uses wide outputs for the regression part (box locations)
        """
        return self.regression_net.conv5.wide

    def are_scores_wide(self):
        """
        Returns whether model uses wide outputs for the classification part (box predictions)
        """
        return self.classication_net.conv5.wide
```

**Comment by MaximGorkem** [comment]
For AI85/AI87, all the input and internal data (activations) are in 8-bits. However, only at the output, you may prefer having your data in 32-bits (see [documentation](https://github.com/MaximIntegratedAI/ai8x-training/#number-format)). We call this feature the wide output. It is quite useful as some classification models suffer from clamping or low quantization resolution (less likely). The extent of its effect on performance depends on some variables, such as the number of classes etc. For example, it is more likely that having wide outputs helps more in CIFAR100 than CIFAR10.

In the FPN model, we use wide outputs in the classification net and 8-bit outputs in the regression net([link](https://github.com/MaximIntegratedAI/ai8x-training/blob/develop/models/ai87-fpndetector.py#L537)). Accordingly, `output_width` parameter of these output layers must be set to 32 in the YAML file of the AI8Xize stage. 

I would not expect the input modality to greatly affect the need for wide-outputs. You can leave the model as is (wide classification & non-wide locations). However, the image size may limit the wide output usage, as the increased resolution means more anchor boxes, so the data memory may not be enough to store 32 bits of the increased number of outputs.

**Comment by nikky4D** [comment]
Thank you for the clarification.
