### ISSUE TITLE
weights and biases initialization

### ISSUE THREAD

**Issue by nikky4D** [MaximIntegratedAI/ai8x-training#253]
I could not find where the CNN weights and biases are initialized. Could you direct me there? and  are the weights and biases in the fpndetector.py all initialized to 0 at the start or if there is a different initialization used?

**Comment by MaximGorkem** [comment]
We use PyTorch's default way of initialization for our layers. For Conv layers, I think it is implemented [here](https://github.com/pytorch/pytorch/blob/main/torch/nn/modules/conv.py#L143).

**Comment by nikky4D** [comment]
Thanks
