### ISSUE TITLE
Cannot find the .yaml file of mine

### ISSUE THREAD

**Issue by liuyuxivapor** [MaximIntegratedAI/ai8x-training#267]
Hi, there. I am creating a new proj of fingerprint recognition. Everything goes well except these 2 things below:
1. `[Errno 2] No such file or directory: 'schedule-fpr.yaml'`though I have made it in the "policies" dir.
2. ``bias` must be set (enable --use-bias for models where bias is optional)` though it might not need bias in the bn step.
Thanks a lot if anyone could help me!

**Comment by alicangok** [comment]
Hi,

Judging by more recent issue at the [synthesis repo](https://github.com/MaximIntegratedAI/ai8x-synthesis/issues/317), I am assuming that you have solved these two small issues regarding running the training script, right?
