### ISSUE TITLE
The datasets issue of FaceID

### ISSUE THREAD

**Issue by jason850124** [MaximIntegratedAI/ai8x-training#273]
Hi,

In recently, I studied about the face recognition, I wanna modify the model of faceid network and retrain it, but I do not know where can download the both of two complete datasets successfully.

Neither VGGFace-2 nor YouTubeFaces can be downloaded.

VGGFace-2 : https://www.robots.ox.ac.uk/~vgg/data/ 
YouTubeFaces : https://www.robots.ox.ac.uk/~vgg/data/

Do you know how I can download above datasets successfully? Thanks!

Best regards,
Jason

**Comment by oguzhanbsolak** [comment]
Hi,

We are planning to update our facial recognition files soon. With the new update, we are planning to end our YouTubeFaces dataset support. For VGGFace-2, the original download links are now dead. You may refer to the [issue](https://github.com/ox-vgg/vgg_face2/issues/52) on the VGGFace-2 repo for more information. Unfortunately, we are not able to provide an alternative download link, but you may search for it on the web.

Regards,
Oğuzhan Büyüksolak

**Comment by jason850124** [comment]
Hi! Oğuzhan,

Thanks for your reply.

I read the issue you mentioned, so both of VGGFace-2 and YouTubeFaces are not working anymore, and I have following questions,

1. For the newer version of facial recognition files, will they modify the model or just use the different dataset?
2. Do you mind provide the dataset which will be used in the newer project?

Best regards,
Jason

**Comment by oguzhanbsolak** [comment]
Hi Jason,

We will proceed with VGGFace-2 support only, the changes will be about methods and models.

Regards,
Oğuzhan Büyüksolak
