### ISSUE TITLE
Resume training for NAS

### ISSUE THREAD

**Issue by daemonkillerr** [MaximIntegratedAI/ai8x-training#281]
Hi, I stopped the training after NAS stage 1 level 1 checkpoint got saved. Now I want to resume training.

Should I:

1. --nas-kd-resume-from logs/2024.01.03-123840/checkpoint.pth.tar --resume-from logs/2024.01.03-123840/nas_stg1_lev1_checkpoint.pth.tar

2. --resume-from logs/2024.01.03-123840/nas_stg1_lev1_checkpoint.pth.tar

Thank you

**Comment by MaximGorkem** [comment]
Second option. You have to call `--resume-from` to continue NAS training.

`--nas-kd-resume-from` is for loading the teacher if you use knowledge distillation with NAS.
