### ISSUE TITLE
ConvTranspose1D support

### ISSUE THREAD

**Issue by MarielTinaco** [MaximIntegratedAI/ai8x-training#290]
Hi All,

I don't know if this is the best place to ask, but I would like to know if there are plans to support ConvTranspose1D based modules in the future. 

I'm working on an event detection problem by applying segmentation on one-dimensional data. Naturally, my first sense is to use UNET architecture but it requires a few deconvolutional layers so I'm thinking of using ConvTranspose1D fused layers. However, it is not supported yet unlike its 2D counter-parts.

Also, is there a recommended way to utilize 2D layers for 1D transformations? For instance, maybe I could hack the ConvTranspose2D layer to work like a ConvTranspose1D layer. How would that translate to synthesis? 

Thanks for your time!

**Comment by rotx-maxim** [comment]
@MarielTinaco, I'm unable to comment on future and non-released features. We have considered the path you're mentioning - it would not be a "general" solution. Could you comment on where you need ConvTranspose1d, and what parameters would need to be supported to make it work for your application.
