### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.object_detection_utils'

### ISSUE THREAD

**Issue by jinx828** [MaximIntegratedAI/ai8x-training#327]
I‘m ture that I followed the "pip install -r requirements.txt"

**Comment by jinx828** [comment]
THERE IS AN DEPRECATION![image](https://github.com/user-attachments/assets/61a6632f-a235-467a-8633-cb2e11157ff7)

**Comment by rotx-eva** [comment]
The deprecation warning should be addressed in #328 

Can you please post more information about the error referenced in the topic of this issue?
