### ISSUE TITLE
bug report: RuntimeError: Cannot find a working triton installation in train.py on Windows10 naitive enviroment 

### ISSUE THREAD

**Issue by sugspi** [MaximIntegratedAI/ai8x-training#329]
Hi, I got torch RuntimeError.
![image](https://github.com/user-attachments/assets/5618c460-af3e-4e2d-bafb-1ecbedce9e98)

I could fix to add code below to train.py.
```   
import torch._dynamo
torch._dynamo.config.suppress_errors = True
```

**Environment**
- OS: windows10 22H2
- python3.11.8
- CUDA 12.3.0
- torch2.3.1+cu121

**Comment by rotx-eva** [comment]
Thanks for letting us know. We will add this to the documentation.
torch.compile() seems to have issues on Windows, see https://github.com/pytorch/pytorch/issues/122094

Without your change, does the example work when you use "--compiler-mode none" ?

**Comment by sugspi** [comment]
I also could run training with "--compiler-mode none", Thanks.

**Comment by rotx-eva** [comment]
Thanks for confirming. We will add this to the documentation.
