### ISSUE TITLE
KeyError conv1.shift_qunatile not found

### ISSUE THREAD

**Issue by flaviose** [MaximIntegratedAI/ai8x-training#334]
Dear All,

when following the instructions in the github page for training and quantizing the mnist model, when evaluating the model after quzantizing it, the error KeyError conv1.shift_qunatile not found.

**Comment by ermanok** [comment]
Hello,

Could you please give more details about the steps you followed and the command you run that causes the error.

Thanks.

**Comment by flaviose** [comment]
Hi, sorry for the late reply , I just followed the instructions on the GitHub exactly using the script provided by the repository instead of me crafting one. The steps that I followed are exactly the ones in the GitHub where mnist is used as an example 

(ai8x-synthesis) $ scripts/quantize_mnist.sh runs as it should but 
(ai8x-training) $ scripts/evaluate_mnist.sh throws the error regarding shift_quantile.

**Comment by flaviose** [comment]
I trained a model myself  When evaluating the resulting models using train.py whenever I use load weights from and a model that has qat_, for example qat_best.pth.tar in the name , I get a state Dict missing keys problem. This happens if  I have a batchnorm layer like in my case the first layer FusedConv2dBNRelu, I don't how the training can generate the qat model but can't load the weights It created, and instead throws the error the loaded checkpoint is missing 4 state keys. The keys missing are 'conv1.bn.weight, cond1.bn.bias, cond1.bn.running_mean, conv1.bn.running_var'

**Comment by asyatrhl** [comment]
Hi, this issue has been resolved in the latest commit. Could you please fetch the ai8x-training repository?
