### ISSUE TITLE
KeyError: 'classification_net.res_conv1.preprocess_layer.output_shift'

### ISSUE THREAD

**Issue by matiasV-TYN** [MaximIntegratedAI/ai8x-training#335]
When running script for pascalvoc fpn object detection demo I encounter KeyError: 'classification_net.res_conv1.preprocess_layer.output_shift'

To reproduce the error:
- $cd ai8x-training
- $source .venv/bin/activate
- $source scripts/evaluate_pascalvoc_fpndetector.sh

The entire log file with full error message is attached.
[log.txt](https://github.com/user-attachments/files/17459555/log.txt)

Troubleshooting tried:
Updated to main branch.
Deleted entire local repository and re-cloned and installed following guide.

Other comments:
- Was also getting another error before this one related to albucore_utils. This error was also happening when trying to run other evaluation scripts. I solved this by downgrading albucore with pip install albucore==0.0.16. After this, other evaluating scripts run fine like for example kws20_v3_ai87. However, when running evaluate_pascalvoc_fpndetector.sh I get error above.
- I am running on a PC with no CUDA so I cant run the training for this demo. But if I remember correctly, I have run the evaluate script for this object_detection demo on this PC before. I also tried lowering the batch-size but error doesn't seem system resources related.

**Comment by ermanok** [comment]
This is a known bug and it is fixed with the PR #331 and the [PR#334 of ai8x-synthesis repo](https://github.com/analogdevicesinc/ai8x-synthesis/pull/354). Please let me know if the error is still exist after checking out those changes.

**Comment by matiasV-TYN** [comment]
> This is a known bug and it is fixed with the PR #331 and the [PR#334 of ai8x-synthesis repo](https://github.com/analogdevicesinc/ai8x-synthesis/pull/354). Please let me know if the error is still exist after checking out those changes.

Now working form qatv2 branch and this is indeed fixed.
Thank you and sorry for duplicate.
