### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by Sandlavish** [MaximIntegratedAI/ai8x-training#98]
Upon following the instructions given in the README file in ai8xtraining/datasets/face_id (https://github.com/MaximIntegratedAI/ai8x-training/tree/master/datasets/face_id), I got an Unbound local error:  local variable 'box' referenced before assignment after I ran the following line of code:
python gen_vggface2_embeddings.py -r <path_to_vggface2_dataset_folder> -d <path_to_store_generated_dataset> --type train

It seems like there's an issue in one of the python files inside the facenet_pytorch folder. 
Thanks.

**Comment by ermanok** [comment]
This bug was already fixed in the submodule repo but it seems submodule path had not been updated in the main repo. For now, you can get the fix by ''git submodule update --recursive --remote --merge''. ai8x-training repo will be fixed soon. Thanks for reporting.

**Comment by rotx-maxim** [comment]
Fixed in #100

**Comment by Sandlavish** [comment]
Hi,
Thanks for all your help but now I am getting an Index Error after I ran the same line of code: 
python gen_vggface2_embeddings.py -r <path_to_vggface2_dataset_folder> -d <path_to_store_generated_dataset> --type train


IndexError: The shape of the mask [58] at index 0 does not match the shape of the indexed tensor [59, 4] at index 0.
